import turtle
screen = turtle.Screen()
screen.bgcolor("white")
t = turtle.Turtle()
t.speed(1)
top_vertex = (0, 100)
right_vertex = (100, -50)
left_vertex = (-100, -50)
t.penup()
t.goto(left_vertex)
t.pendown()
t.goto(right_vertex)
t.goto(top_vertex)
t.goto(left_vertex)
t.fillcolor("blue")
t.begin_fill()
t.goto(0,0)
t.goto(right_vertex)
t.goto(left_vertex)
t.end_fill()
t.hideturtle()
turtle.done()
